import type { Vehicle } from "@/types"

export const vehicles: Vehicle[] = [
  {
    id: "1",
    name: "Camión grúa - Iveco",
    type: "crane",
    images: [
      "/grua-iveco.png?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    currency: "USD",
    pricePerDay: 850,
    location: "Santo Domingo",
    available: true,
    hasInsurance: true,
    capacity: "200 tons",
    year: 2020,
    fuelType: "Diesel",
    rating: 4.8,
    description:
      "Professional heavy-duty mobile crane perfect for construction and industrial projects. Features advanced safety systems and experienced operator available.",
  },
  {
    id: "2",
    name: "Grúa Canastillas",
    type: "truck",
    images: [
      "/grua-canastilla-telescópica.jpeg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    currency: "DOP",
    pricePerDay: 11700,
    location: "Punta Cana",
    available: true,
    hasInsurance: false,
    capacity: "40 tons",
    year: 2019,
    fuelType: "Diesel",
    rating: 4.5,
    description:
      "Reliable flatbed truck ideal for transporting heavy machinery, construction materials, and oversized cargo.",
  },
  {
    id: "3",
    name: "Grúa con Rampa",
    type: "crane",
    images: [
      "/grua-rampa-frod-8000.jpg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    currency: "DOP",
    pricePerDay: 18000,
    location: "Santiago",
    available: true,
    hasInsurance: true,
    capacity: "150 tons",
    year: 2021,
    fuelType: "Diesel",
    rating: 4.7,
    description:
      "Versatile rough terrain crane with excellent mobility and lifting capacity for various construction applications.",
  },
  {
    id: "4",
    name: "Semi Trailer - Freightliner Cascadia",
    type: "trailer",
    images: [
      "/grua-plataforma-loaded.webp?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    currency: "DOP",
    pricePerDay: 17000,
    location: "Barahona",
    available: false,
    hasInsurance: true,
    capacity: "80,000 lbs",
    year: 2018,
    fuelType: "Diesel",
    rating: 4.3,
    description: "Long-haul semi-trailer perfect for interstate transportation of goods and materials.",
  },
  {
    id: "5",
    name: "Camión grúa - Stinger",
    type: "excavator",
    images: [
      "/camion-grua-stinger.png?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    currency: "DOP",
    pricePerDay: 25000,
    location: "Distrito Nacional",
    available: true,
    hasInsurance: false,
    capacity: "36 tons",
    year: 2020,
    fuelType: "Diesel",
    rating: 4.6,
    description: "Heavy-duty excavator suitable for earthmoving, demolition, and construction projects.",
  },
  {
    id: "6",
    name: "Dump Truck - Mack Granite",
    type: "truck",
    images: [
      "/grua-remolque.png?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    currency: "DOP",
    pricePerDay: 35000,
    location: "San Cristóbal",
    available: true,
    hasInsurance: true,
    capacity: "25 cubic yards",
    year: 2019,
    fuelType: "Diesel",
    rating: 4.4,
    description: "Robust dump truck perfect for hauling sand, gravel, dirt, and other construction materials.",
  },
]
